### ISSUE TITLE
Installable ?

### ISSUE THREAD

**Issue by AntoineTurmel** [nt1m/thunderbird-icons#1]
Nice idea ! Will this be part of a TB theme or is it going to be shipped in a future version of TB ?

**Comment by nt1m** [comment]
@AntoineTurmel They're being integrated in TB: https://bugzilla.mozilla.org/show_bug.cgi?id=1427509

**Comment by AntoineTurmel** [comment]
Nice, thanks !

**Comment by nt1m** [comment]
@AntoineTurmel They just arrived in the latest thunderbird daily build :)

http://ftp.mozilla.org/pub/thunderbird/nightly/latest-comm-central/

**Comment by AntoineTurmel** [comment]
@nt1m thanks i'll try ! Any idea when this will be in beta channel ? (that's the main channel I use)

**Comment by nt1m** [comment]
Normally, they should arrive in 10 days on beta.
